export const VOCATIONAL_SKILLS = [
  "Retail",
  "Information Technology",
  "Web Application",
  "Automotive",
  "Financial Markets Management",
  "Tourism",
  "Beauty & Wellness",
  "Agriculture",
  "Food Production",
  "Front Office Operations",
  "Banking",
  "Marketing",
  "Health Care",
  "Insurance",
  "Horticulture",
  "Typography & Comp. Application",
  "Geospatial Technology",
  "Electrical Technology",
  "Electronic Technology",
  "Multi-Media",
  "Taxation",
  "Cost Accounting",
  "Office Procedures & Practices",
  "Shorthand (English)",
  "Shorthand (Hindi)",
  "Air-conditioning & Refrigeration",
  "Medical Diagnostics",
  "Textile Design",
  "Design",
  "Salesmanship",
  "Business Administration",
  "Food Nutrition & Dietetics",
  "Mass Media Studies",
  "Library & Information Science",
  "Fashion Studies",
  "Yoga",
  "Early Childhood Care & Education",
  "Artificial Intelligence",
  "Data Science",
  "Physical Activity Trainer",
  "Land Transportation Associate",
  "Electronics & Hardware",
  "Design Thinking & Innovation"
].sort((a, b) => a.localeCompare(b));
